import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { RGBELoader } from 'three/addons/loaders/RGBELoader.js';
import { ENVIRONMENTS, HDRI_BASE_URL } from '../config.js';

/**
 * Image-based lighting for the viewport.
 *
 * Directional lights alone leave metals looking flat: a high-metalness surface
 * has almost no diffuse response, so with nothing to reflect it renders near
 * black except where a light hits it dead on. An environment map gives those
 * surfaces something to mirror, which is what makes car paint and chrome read
 * as metal.
 *
 * Two sources are supported:
 *
 *  - `room`, a procedural studio generated by three.js. No network request, so
 *    it is the default and always works offline.
 *  - Poly Haven CC0 HDRIs, fetched on demand and cached.
 *
 * Every map is prefiltered through PMREMGenerator, which is what turns a raw
 * equirectangular image into the roughness-aware mip chain the standard
 * material samples.
 */
export class EnvironmentManager {
  /**
   * @param {THREE.WebGLRenderer} renderer
   * @param {THREE.Scene} scene
   */
  constructor(renderer, scene) {
    this.scene = scene;
    this.pmrem = new THREE.PMREMGenerator(renderer);
    this.pmrem.compileEquirectangularShader();

    /** @type {Map<string, THREE.WebGLRenderTarget>} id -> prefiltered target. */
    this.cache = new Map();
    this.currentId = 'none';

    // Guards against a slow HDRI landing after the user picked something else.
    this.requestToken = 0;
  }

  /** Builds the procedural studio: soft area lights in a neutral room. */
  createRoomTarget() {
    const room = new RoomEnvironment();
    const target = this.pmrem.fromScene(room, 0.04);
    room.dispose();
    return target;
  }

  /** Fetches and prefilters a Poly Haven HDRI. */
  async createHdriTarget(file) {
    const texture = await new RGBELoader().loadAsync(`${HDRI_BASE_URL}/${file}`);
    texture.mapping = THREE.EquirectangularReflectionMapping;

    const target = this.pmrem.fromEquirectangular(texture);
    // The prefiltered target is what gets sampled; the source is dead weight.
    texture.dispose();
    return target;
  }

  /**
   * Applies an environment by id, fetching it if this is the first request.
   *
   * A failed HDRI download is not fatal — it falls back to the built-in studio
   * so the viewport keeps working offline or when Poly Haven is unreachable.
   *
   * @param {string} id Key into ENVIRONMENTS.
   * @param {(status: string) => void} [onStatus] Progress reporter.
   * @returns {Promise<{id: string, fellBack: boolean, error?: string}>}
   */
  async apply(id, onStatus) {
    const token = ++this.requestToken;
    const preset = ENVIRONMENTS[id];

    if (!preset || id === 'none') {
      this.scene.environment = null;
      this.currentId = 'none';
      return { id: 'none', fellBack: false };
    }

    if (this.cache.has(id)) {
      this.scene.environment = this.cache.get(id).texture;
      this.currentId = id;
      return { id, fellBack: false };
    }

    try {
      let target;
      if (preset.file) {
        onStatus?.(`Loading ${preset.label} environment…`);
        target = await this.createHdriTarget(preset.file);
      } else {
        target = this.createRoomTarget();
      }

      // A newer selection won the race while this was in flight.
      if (token !== this.requestToken) {
        target.dispose();
        return { id: this.currentId, fellBack: false };
      }

      this.cache.set(id, target);
      this.scene.environment = target.texture;
      this.currentId = id;
      return { id, fellBack: false };
    } catch (err) {
      console.warn(`Environment "${id}" failed to load; using the built-in studio.`, err);
      if (token !== this.requestToken) return { id: this.currentId, fellBack: false };

      const fallback = await this.apply('studio');
      return { id: fallback.id, fellBack: true, error: err.message };
    }
  }

  dispose() {
    this.cache.forEach((target) => target.dispose());
    this.cache.clear();
    this.pmrem.dispose();
    this.scene.environment = null;
  }
}
